### ISSUE TITLE
Can not define method in subclass of NamedTuple

### ISSUE THREAD

**Issue by ADR-007** [python/typing#411]
I can define method when i use subclass of `NamedTuple('example', (('aaa', int), ('bbb', float)))` but it doesn't work in Python 3.6 style of NamedTuple:

```
from typing import NamedTuple


class NT(NamedTuple):
    aaa: int
    bbb: float

    def ab(self):
        print(2)


NT(1, 0.5).ab()
```

Result:
```
Traceback (most recent call last):
  File ".../tmp.py", line 12, in <module>
    NT(1, 0.5).ab()
AttributeError: 'NT' object has no attribute 'ab'
```

**Comment by ilevkivskyi** [comment]
Which version or Python/typing are you using? I just tried this on master and it works. If you are using 3.6.0, then try upgrading to 3.6.1, or maybe try the master branch (this was fixed only recently IIRC).

**Comment by ADR-007** [comment]
Yes, its really work in python 3.6.1! Thanks!

But what about "__new__" and "__init__" methods? Why I can't use their? It can be helpful when you want to set any mutable objects as default value (like "list" or "dict"). Of course I can use any other name for custom constructor.

**Comment by ilevkivskyi** [comment]
``__init__`` and ``__new__`` are a bit more difficult to tweak due to the way they are defined in the underlying ``collections.namedtuple`` implementation. As a workaround, you could update (monkey-patch) ``__init__`` _after_ named tuple class is created.
